/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FindMyService {
    'categories': string;
    'layers': string;
  }
}

declare global {


  interface HTMLFindMyServiceElement extends Components.FindMyService, HTMLStencilElement {}
  var HTMLFindMyServiceElement: {
    prototype: HTMLFindMyServiceElement;
    new (): HTMLFindMyServiceElement;
  };
  interface HTMLElementTagNameMap {
    'find-my-service': HTMLFindMyServiceElement;
  }
}

declare namespace LocalJSX {
  interface FindMyService extends JSXBase.HTMLAttributes<HTMLFindMyServiceElement> {
    'categories'?: string;
    'layers'?: string;
  }

  interface IntrinsicElements {
    'find-my-service': FindMyService;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


